namespace DORMITORY_MANAGEMENT
{
    partial class Settings
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Settings));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.btn_SavedStaffInfors = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_StaffSalary = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_StaffAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_StaffPersonalID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_StaffPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_StaffName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_StaffID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.btn_SavedLoginInfor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_RetypeNewPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_NewPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_StaffEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 8;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.btn_SavedStaffInfors);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel6);
            this.bunifuGroupBox1.Controls.Add(this.txt_StaffSalary);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel5);
            this.bunifuGroupBox1.Controls.Add(this.txt_StaffAddress);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel4);
            this.bunifuGroupBox1.Controls.Add(this.txt_StaffPersonalID);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel3);
            this.bunifuGroupBox1.Controls.Add(this.txt_StaffPhone);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel2);
            this.bunifuGroupBox1.Controls.Add(this.txt_StaffName);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel1);
            this.bunifuGroupBox1.Controls.Add(this.txt_StaffID);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(19, 18);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(1100, 343);
            this.bunifuGroupBox1.TabIndex = 0;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Thông tin cá nhân";
            // 
            // btn_SavedStaffInfors
            // 
            this.btn_SavedStaffInfors.AllowAnimations = true;
            this.btn_SavedStaffInfors.AllowMouseEffects = true;
            this.btn_SavedStaffInfors.AllowToggling = false;
            this.btn_SavedStaffInfors.AnimationSpeed = 200;
            this.btn_SavedStaffInfors.AutoGenerateColors = false;
            this.btn_SavedStaffInfors.AutoRoundBorders = false;
            this.btn_SavedStaffInfors.AutoSizeLeftIcon = true;
            this.btn_SavedStaffInfors.AutoSizeRightIcon = true;
            this.btn_SavedStaffInfors.BackColor = System.Drawing.Color.Transparent;
            this.btn_SavedStaffInfors.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedStaffInfors.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_SavedStaffInfors.BackgroundImage")));
            this.btn_SavedStaffInfors.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedStaffInfors.ButtonText = "Lưu";
            this.btn_SavedStaffInfors.ButtonTextMarginLeft = 0;
            this.btn_SavedStaffInfors.ColorContrastOnClick = 45;
            this.btn_SavedStaffInfors.ColorContrastOnHover = 45;
            this.btn_SavedStaffInfors.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_SavedStaffInfors.CustomizableEdges = borderEdges1;
            this.btn_SavedStaffInfors.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_SavedStaffInfors.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SavedStaffInfors.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SavedStaffInfors.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SavedStaffInfors.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_SavedStaffInfors.Font = new System.Drawing.Font("Segoe UI Semibold", 13.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_SavedStaffInfors.ForeColor = System.Drawing.Color.White;
            this.btn_SavedStaffInfors.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_SavedStaffInfors.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_SavedStaffInfors.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_SavedStaffInfors.IconMarginLeft = 11;
            this.btn_SavedStaffInfors.IconPadding = 10;
            this.btn_SavedStaffInfors.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_SavedStaffInfors.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_SavedStaffInfors.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_SavedStaffInfors.IconSize = 25;
            this.btn_SavedStaffInfors.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedStaffInfors.IdleBorderRadius = 10;
            this.btn_SavedStaffInfors.IdleBorderThickness = 1;
            this.btn_SavedStaffInfors.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedStaffInfors.IdleIconLeftImage = null;
            this.btn_SavedStaffInfors.IdleIconRightImage = null;
            this.btn_SavedStaffInfors.IndicateFocus = false;
            this.btn_SavedStaffInfors.Location = new System.Drawing.Point(1007, 272);
            this.btn_SavedStaffInfors.Name = "btn_SavedStaffInfors";
            this.btn_SavedStaffInfors.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SavedStaffInfors.OnDisabledState.BorderRadius = 10;
            this.btn_SavedStaffInfors.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedStaffInfors.OnDisabledState.BorderThickness = 1;
            this.btn_SavedStaffInfors.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SavedStaffInfors.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SavedStaffInfors.OnDisabledState.IconLeftImage = null;
            this.btn_SavedStaffInfors.OnDisabledState.IconRightImage = null;
            this.btn_SavedStaffInfors.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(181)))), ((int)(((byte)(116)))));
            this.btn_SavedStaffInfors.onHoverState.BorderRadius = 10;
            this.btn_SavedStaffInfors.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedStaffInfors.onHoverState.BorderThickness = 1;
            this.btn_SavedStaffInfors.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(181)))), ((int)(((byte)(116)))));
            this.btn_SavedStaffInfors.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_SavedStaffInfors.onHoverState.IconLeftImage = null;
            this.btn_SavedStaffInfors.onHoverState.IconRightImage = null;
            this.btn_SavedStaffInfors.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedStaffInfors.OnIdleState.BorderRadius = 10;
            this.btn_SavedStaffInfors.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedStaffInfors.OnIdleState.BorderThickness = 1;
            this.btn_SavedStaffInfors.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedStaffInfors.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_SavedStaffInfors.OnIdleState.IconLeftImage = null;
            this.btn_SavedStaffInfors.OnIdleState.IconRightImage = null;
            this.btn_SavedStaffInfors.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedStaffInfors.OnPressedState.BorderRadius = 10;
            this.btn_SavedStaffInfors.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedStaffInfors.OnPressedState.BorderThickness = 1;
            this.btn_SavedStaffInfors.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedStaffInfors.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_SavedStaffInfors.OnPressedState.IconLeftImage = null;
            this.btn_SavedStaffInfors.OnPressedState.IconRightImage = null;
            this.btn_SavedStaffInfors.Size = new System.Drawing.Size(77, 50);
            this.btn_SavedStaffInfors.TabIndex = 130;
            this.btn_SavedStaffInfors.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_SavedStaffInfors.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_SavedStaffInfors.TextMarginLeft = 0;
            this.btn_SavedStaffInfors.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_SavedStaffInfors.UseDefaultRadiusAndThickness = true;
            this.btn_SavedStaffInfors.Click += new System.EventHandler(this.btn_SavedStaffInfors_Click);
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(784, 151);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(42, 20);
            this.bunifuLabel6.TabIndex = 16;
            this.bunifuLabel6.Text = "Lương";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_StaffSalary
            // 
            this.txt_StaffSalary.AcceptsReturn = false;
            this.txt_StaffSalary.AcceptsTab = false;
            this.txt_StaffSalary.AnimationSpeed = 200;
            this.txt_StaffSalary.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_StaffSalary.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_StaffSalary.BackColor = System.Drawing.Color.Transparent;
            this.txt_StaffSalary.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_StaffSalary.BackgroundImage")));
            this.txt_StaffSalary.BorderColorActive = System.Drawing.Color.White;
            this.txt_StaffSalary.BorderColorDisabled = System.Drawing.Color.White;
            this.txt_StaffSalary.BorderColorHover = System.Drawing.Color.White;
            this.txt_StaffSalary.BorderColorIdle = System.Drawing.Color.White;
            this.txt_StaffSalary.BorderRadius = 10;
            this.txt_StaffSalary.BorderThickness = 1;
            this.txt_StaffSalary.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_StaffSalary.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffSalary.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_StaffSalary.DefaultText = "";
            this.txt_StaffSalary.Enabled = false;
            this.txt_StaffSalary.FillColor = System.Drawing.Color.White;
            this.txt_StaffSalary.HideSelection = true;
            this.txt_StaffSalary.IconLeft = null;
            this.txt_StaffSalary.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffSalary.IconPadding = 10;
            this.txt_StaffSalary.IconRight = null;
            this.txt_StaffSalary.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffSalary.Lines = new string[0];
            this.txt_StaffSalary.Location = new System.Drawing.Point(784, 177);
            this.txt_StaffSalary.MaxLength = 32767;
            this.txt_StaffSalary.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_StaffSalary.Modified = false;
            this.txt_StaffSalary.Multiline = false;
            this.txt_StaffSalary.Name = "txt_StaffSalary";
            stateProperties1.BorderColor = System.Drawing.Color.White;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffSalary.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.White;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_StaffSalary.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.White;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffSalary.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.White;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffSalary.OnIdleState = stateProperties4;
            this.txt_StaffSalary.Padding = new System.Windows.Forms.Padding(3);
            this.txt_StaffSalary.PasswordChar = '\0';
            this.txt_StaffSalary.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(85)))), ((int)(((byte)(90)))));
            this.txt_StaffSalary.PlaceholderText = "Lương";
            this.txt_StaffSalary.ReadOnly = false;
            this.txt_StaffSalary.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_StaffSalary.SelectedText = "";
            this.txt_StaffSalary.SelectionLength = 0;
            this.txt_StaffSalary.SelectionStart = 0;
            this.txt_StaffSalary.ShortcutsEnabled = true;
            this.txt_StaffSalary.Size = new System.Drawing.Size(300, 50);
            this.txt_StaffSalary.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_StaffSalary.TabIndex = 15;
            this.txt_StaffSalary.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_StaffSalary.TextMarginBottom = 0;
            this.txt_StaffSalary.TextMarginLeft = 10;
            this.txt_StaffSalary.TextMarginTop = 0;
            this.txt_StaffSalary.TextPlaceholder = "Lương";
            this.txt_StaffSalary.UseSystemPasswordChar = false;
            this.txt_StaffSalary.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(408, 151);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(46, 20);
            this.bunifuLabel5.TabIndex = 14;
            this.bunifuLabel5.Text = "Địa chỉ";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_StaffAddress
            // 
            this.txt_StaffAddress.AcceptsReturn = false;
            this.txt_StaffAddress.AcceptsTab = false;
            this.txt_StaffAddress.AnimationSpeed = 200;
            this.txt_StaffAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_StaffAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_StaffAddress.BackColor = System.Drawing.Color.Transparent;
            this.txt_StaffAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_StaffAddress.BackgroundImage")));
            this.txt_StaffAddress.BorderColorActive = System.Drawing.Color.White;
            this.txt_StaffAddress.BorderColorDisabled = System.Drawing.Color.White;
            this.txt_StaffAddress.BorderColorHover = System.Drawing.Color.White;
            this.txt_StaffAddress.BorderColorIdle = System.Drawing.Color.White;
            this.txt_StaffAddress.BorderRadius = 10;
            this.txt_StaffAddress.BorderThickness = 1;
            this.txt_StaffAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_StaffAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_StaffAddress.DefaultText = "";
            this.txt_StaffAddress.FillColor = System.Drawing.Color.White;
            this.txt_StaffAddress.HideSelection = true;
            this.txt_StaffAddress.IconLeft = null;
            this.txt_StaffAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffAddress.IconPadding = 10;
            this.txt_StaffAddress.IconRight = null;
            this.txt_StaffAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffAddress.Lines = new string[0];
            this.txt_StaffAddress.Location = new System.Drawing.Point(408, 177);
            this.txt_StaffAddress.MaxLength = 32767;
            this.txt_StaffAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_StaffAddress.Modified = false;
            this.txt_StaffAddress.Multiline = false;
            this.txt_StaffAddress.Name = "txt_StaffAddress";
            stateProperties5.BorderColor = System.Drawing.Color.White;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffAddress.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.White;
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_StaffAddress.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.White;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffAddress.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.White;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffAddress.OnIdleState = stateProperties8;
            this.txt_StaffAddress.Padding = new System.Windows.Forms.Padding(3);
            this.txt_StaffAddress.PasswordChar = '\0';
            this.txt_StaffAddress.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(85)))), ((int)(((byte)(90)))));
            this.txt_StaffAddress.PlaceholderText = "Địa chỉ";
            this.txt_StaffAddress.ReadOnly = false;
            this.txt_StaffAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_StaffAddress.SelectedText = "";
            this.txt_StaffAddress.SelectionLength = 0;
            this.txt_StaffAddress.SelectionStart = 0;
            this.txt_StaffAddress.ShortcutsEnabled = true;
            this.txt_StaffAddress.Size = new System.Drawing.Size(300, 50);
            this.txt_StaffAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_StaffAddress.TabIndex = 13;
            this.txt_StaffAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_StaffAddress.TextMarginBottom = 0;
            this.txt_StaffAddress.TextMarginLeft = 10;
            this.txt_StaffAddress.TextMarginTop = 0;
            this.txt_StaffAddress.TextPlaceholder = "Địa chỉ";
            this.txt_StaffAddress.UseSystemPasswordChar = false;
            this.txt_StaffAddress.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(25, 151);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(146, 20);
            this.bunifuLabel4.TabIndex = 12;
            this.bunifuLabel4.Text = "Số căn cước công dân";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_StaffPersonalID
            // 
            this.txt_StaffPersonalID.AcceptsReturn = false;
            this.txt_StaffPersonalID.AcceptsTab = false;
            this.txt_StaffPersonalID.AnimationSpeed = 200;
            this.txt_StaffPersonalID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_StaffPersonalID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_StaffPersonalID.BackColor = System.Drawing.Color.Transparent;
            this.txt_StaffPersonalID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_StaffPersonalID.BackgroundImage")));
            this.txt_StaffPersonalID.BorderColorActive = System.Drawing.Color.White;
            this.txt_StaffPersonalID.BorderColorDisabled = System.Drawing.Color.White;
            this.txt_StaffPersonalID.BorderColorHover = System.Drawing.Color.White;
            this.txt_StaffPersonalID.BorderColorIdle = System.Drawing.Color.White;
            this.txt_StaffPersonalID.BorderRadius = 10;
            this.txt_StaffPersonalID.BorderThickness = 1;
            this.txt_StaffPersonalID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_StaffPersonalID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffPersonalID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_StaffPersonalID.DefaultText = "";
            this.txt_StaffPersonalID.FillColor = System.Drawing.Color.White;
            this.txt_StaffPersonalID.HideSelection = true;
            this.txt_StaffPersonalID.IconLeft = null;
            this.txt_StaffPersonalID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffPersonalID.IconPadding = 10;
            this.txt_StaffPersonalID.IconRight = null;
            this.txt_StaffPersonalID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffPersonalID.Lines = new string[0];
            this.txt_StaffPersonalID.Location = new System.Drawing.Point(25, 177);
            this.txt_StaffPersonalID.MaxLength = 32767;
            this.txt_StaffPersonalID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_StaffPersonalID.Modified = false;
            this.txt_StaffPersonalID.Multiline = false;
            this.txt_StaffPersonalID.Name = "txt_StaffPersonalID";
            stateProperties9.BorderColor = System.Drawing.Color.White;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffPersonalID.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.White;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_StaffPersonalID.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.White;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffPersonalID.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.White;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffPersonalID.OnIdleState = stateProperties12;
            this.txt_StaffPersonalID.Padding = new System.Windows.Forms.Padding(3);
            this.txt_StaffPersonalID.PasswordChar = '\0';
            this.txt_StaffPersonalID.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(85)))), ((int)(((byte)(90)))));
            this.txt_StaffPersonalID.PlaceholderText = "Số căn cước công dân";
            this.txt_StaffPersonalID.ReadOnly = false;
            this.txt_StaffPersonalID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_StaffPersonalID.SelectedText = "";
            this.txt_StaffPersonalID.SelectionLength = 0;
            this.txt_StaffPersonalID.SelectionStart = 0;
            this.txt_StaffPersonalID.ShortcutsEnabled = true;
            this.txt_StaffPersonalID.Size = new System.Drawing.Size(300, 50);
            this.txt_StaffPersonalID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_StaffPersonalID.TabIndex = 11;
            this.txt_StaffPersonalID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_StaffPersonalID.TextMarginBottom = 0;
            this.txt_StaffPersonalID.TextMarginLeft = 10;
            this.txt_StaffPersonalID.TextMarginTop = 0;
            this.txt_StaffPersonalID.TextPlaceholder = "Số căn cước công dân";
            this.txt_StaffPersonalID.UseSystemPasswordChar = false;
            this.txt_StaffPersonalID.WordWrap = true;
            this.txt_StaffPersonalID.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_StaffPersonalID_KeyPress);
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(784, 37);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(88, 20);
            this.bunifuLabel3.TabIndex = 10;
            this.bunifuLabel3.Text = "Số điện thoại";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_StaffPhone
            // 
            this.txt_StaffPhone.AcceptsReturn = false;
            this.txt_StaffPhone.AcceptsTab = false;
            this.txt_StaffPhone.AnimationSpeed = 200;
            this.txt_StaffPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_StaffPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_StaffPhone.BackColor = System.Drawing.Color.Transparent;
            this.txt_StaffPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_StaffPhone.BackgroundImage")));
            this.txt_StaffPhone.BorderColorActive = System.Drawing.Color.White;
            this.txt_StaffPhone.BorderColorDisabled = System.Drawing.Color.White;
            this.txt_StaffPhone.BorderColorHover = System.Drawing.Color.White;
            this.txt_StaffPhone.BorderColorIdle = System.Drawing.Color.White;
            this.txt_StaffPhone.BorderRadius = 10;
            this.txt_StaffPhone.BorderThickness = 1;
            this.txt_StaffPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_StaffPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_StaffPhone.DefaultText = "";
            this.txt_StaffPhone.FillColor = System.Drawing.Color.White;
            this.txt_StaffPhone.HideSelection = true;
            this.txt_StaffPhone.IconLeft = null;
            this.txt_StaffPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffPhone.IconPadding = 10;
            this.txt_StaffPhone.IconRight = null;
            this.txt_StaffPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffPhone.Lines = new string[0];
            this.txt_StaffPhone.Location = new System.Drawing.Point(784, 63);
            this.txt_StaffPhone.MaxLength = 32767;
            this.txt_StaffPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_StaffPhone.Modified = false;
            this.txt_StaffPhone.Multiline = false;
            this.txt_StaffPhone.Name = "txt_StaffPhone";
            stateProperties13.BorderColor = System.Drawing.Color.White;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffPhone.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.White;
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_StaffPhone.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.White;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffPhone.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.White;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffPhone.OnIdleState = stateProperties16;
            this.txt_StaffPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txt_StaffPhone.PasswordChar = '\0';
            this.txt_StaffPhone.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(85)))), ((int)(((byte)(90)))));
            this.txt_StaffPhone.PlaceholderText = "Số điện thoại";
            this.txt_StaffPhone.ReadOnly = false;
            this.txt_StaffPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_StaffPhone.SelectedText = "";
            this.txt_StaffPhone.SelectionLength = 0;
            this.txt_StaffPhone.SelectionStart = 0;
            this.txt_StaffPhone.ShortcutsEnabled = true;
            this.txt_StaffPhone.Size = new System.Drawing.Size(300, 50);
            this.txt_StaffPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_StaffPhone.TabIndex = 9;
            this.txt_StaffPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_StaffPhone.TextMarginBottom = 0;
            this.txt_StaffPhone.TextMarginLeft = 10;
            this.txt_StaffPhone.TextMarginTop = 0;
            this.txt_StaffPhone.TextPlaceholder = "Số điện thoại";
            this.txt_StaffPhone.UseSystemPasswordChar = false;
            this.txt_StaffPhone.WordWrap = true;
            this.txt_StaffPhone.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_StaffPhone_KeyPress);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(408, 37);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(64, 20);
            this.bunifuLabel2.TabIndex = 8;
            this.bunifuLabel2.Text = "Họ và tên";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_StaffName
            // 
            this.txt_StaffName.AcceptsReturn = false;
            this.txt_StaffName.AcceptsTab = false;
            this.txt_StaffName.AnimationSpeed = 200;
            this.txt_StaffName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_StaffName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_StaffName.BackColor = System.Drawing.Color.Transparent;
            this.txt_StaffName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_StaffName.BackgroundImage")));
            this.txt_StaffName.BorderColorActive = System.Drawing.Color.White;
            this.txt_StaffName.BorderColorDisabled = System.Drawing.Color.White;
            this.txt_StaffName.BorderColorHover = System.Drawing.Color.White;
            this.txt_StaffName.BorderColorIdle = System.Drawing.Color.White;
            this.txt_StaffName.BorderRadius = 10;
            this.txt_StaffName.BorderThickness = 1;
            this.txt_StaffName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_StaffName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_StaffName.DefaultText = "";
            this.txt_StaffName.FillColor = System.Drawing.Color.White;
            this.txt_StaffName.HideSelection = true;
            this.txt_StaffName.IconLeft = null;
            this.txt_StaffName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffName.IconPadding = 10;
            this.txt_StaffName.IconRight = null;
            this.txt_StaffName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffName.Lines = new string[0];
            this.txt_StaffName.Location = new System.Drawing.Point(408, 63);
            this.txt_StaffName.MaxLength = 32767;
            this.txt_StaffName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_StaffName.Modified = false;
            this.txt_StaffName.Multiline = false;
            this.txt_StaffName.Name = "txt_StaffName";
            stateProperties17.BorderColor = System.Drawing.Color.White;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.White;
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_StaffName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.White;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.White;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffName.OnIdleState = stateProperties20;
            this.txt_StaffName.Padding = new System.Windows.Forms.Padding(3);
            this.txt_StaffName.PasswordChar = '\0';
            this.txt_StaffName.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(85)))), ((int)(((byte)(90)))));
            this.txt_StaffName.PlaceholderText = "Họ và tên";
            this.txt_StaffName.ReadOnly = false;
            this.txt_StaffName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_StaffName.SelectedText = "";
            this.txt_StaffName.SelectionLength = 0;
            this.txt_StaffName.SelectionStart = 0;
            this.txt_StaffName.ShortcutsEnabled = true;
            this.txt_StaffName.Size = new System.Drawing.Size(300, 50);
            this.txt_StaffName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_StaffName.TabIndex = 7;
            this.txt_StaffName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_StaffName.TextMarginBottom = 0;
            this.txt_StaffName.TextMarginLeft = 10;
            this.txt_StaffName.TextMarginTop = 0;
            this.txt_StaffName.TextPlaceholder = "Họ và tên";
            this.txt_StaffName.UseSystemPasswordChar = false;
            this.txt_StaffName.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(25, 37);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(15, 20);
            this.bunifuLabel1.TabIndex = 6;
            this.bunifuLabel1.Text = "ID";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_StaffID
            // 
            this.txt_StaffID.AcceptsReturn = false;
            this.txt_StaffID.AcceptsTab = false;
            this.txt_StaffID.AnimationSpeed = 200;
            this.txt_StaffID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_StaffID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_StaffID.BackColor = System.Drawing.Color.Transparent;
            this.txt_StaffID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_StaffID.BackgroundImage")));
            this.txt_StaffID.BorderColorActive = System.Drawing.Color.White;
            this.txt_StaffID.BorderColorDisabled = System.Drawing.Color.White;
            this.txt_StaffID.BorderColorHover = System.Drawing.Color.White;
            this.txt_StaffID.BorderColorIdle = System.Drawing.Color.White;
            this.txt_StaffID.BorderRadius = 10;
            this.txt_StaffID.BorderThickness = 1;
            this.txt_StaffID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_StaffID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_StaffID.DefaultText = "";
            this.txt_StaffID.Enabled = false;
            this.txt_StaffID.FillColor = System.Drawing.Color.White;
            this.txt_StaffID.HideSelection = true;
            this.txt_StaffID.IconLeft = null;
            this.txt_StaffID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffID.IconPadding = 10;
            this.txt_StaffID.IconRight = null;
            this.txt_StaffID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffID.Lines = new string[0];
            this.txt_StaffID.Location = new System.Drawing.Point(25, 63);
            this.txt_StaffID.MaxLength = 32767;
            this.txt_StaffID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_StaffID.Modified = false;
            this.txt_StaffID.Multiline = false;
            this.txt_StaffID.Name = "txt_StaffID";
            stateProperties21.BorderColor = System.Drawing.Color.White;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffID.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.White;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_StaffID.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.White;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffID.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.White;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffID.OnIdleState = stateProperties24;
            this.txt_StaffID.Padding = new System.Windows.Forms.Padding(3);
            this.txt_StaffID.PasswordChar = '\0';
            this.txt_StaffID.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(85)))), ((int)(((byte)(90)))));
            this.txt_StaffID.PlaceholderText = "ID";
            this.txt_StaffID.ReadOnly = false;
            this.txt_StaffID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_StaffID.SelectedText = "";
            this.txt_StaffID.SelectionLength = 0;
            this.txt_StaffID.SelectionStart = 0;
            this.txt_StaffID.ShortcutsEnabled = true;
            this.txt_StaffID.Size = new System.Drawing.Size(300, 50);
            this.txt_StaffID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_StaffID.TabIndex = 5;
            this.txt_StaffID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_StaffID.TextMarginBottom = 0;
            this.txt_StaffID.TextMarginLeft = 10;
            this.txt_StaffID.TextMarginTop = 0;
            this.txt_StaffID.TextPlaceholder = "ID";
            this.txt_StaffID.UseSystemPasswordChar = false;
            this.txt_StaffID.WordWrap = true;
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 8;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.btn_SavedLoginInfor);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel9);
            this.bunifuGroupBox2.Controls.Add(this.txt_RetypeNewPassword);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel8);
            this.bunifuGroupBox2.Controls.Add(this.txt_NewPassword);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel7);
            this.bunifuGroupBox2.Controls.Add(this.txt_StaffEmail);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(19, 402);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(1100, 354);
            this.bunifuGroupBox2.TabIndex = 1;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Thông tin đăng nhập";
            // 
            // btn_SavedLoginInfor
            // 
            this.btn_SavedLoginInfor.AllowAnimations = true;
            this.btn_SavedLoginInfor.AllowMouseEffects = true;
            this.btn_SavedLoginInfor.AllowToggling = false;
            this.btn_SavedLoginInfor.AnimationSpeed = 200;
            this.btn_SavedLoginInfor.AutoGenerateColors = false;
            this.btn_SavedLoginInfor.AutoRoundBorders = false;
            this.btn_SavedLoginInfor.AutoSizeLeftIcon = true;
            this.btn_SavedLoginInfor.AutoSizeRightIcon = true;
            this.btn_SavedLoginInfor.BackColor = System.Drawing.Color.Transparent;
            this.btn_SavedLoginInfor.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedLoginInfor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_SavedLoginInfor.BackgroundImage")));
            this.btn_SavedLoginInfor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedLoginInfor.ButtonText = "Lưu";
            this.btn_SavedLoginInfor.ButtonTextMarginLeft = 0;
            this.btn_SavedLoginInfor.ColorContrastOnClick = 45;
            this.btn_SavedLoginInfor.ColorContrastOnHover = 45;
            this.btn_SavedLoginInfor.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_SavedLoginInfor.CustomizableEdges = borderEdges2;
            this.btn_SavedLoginInfor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_SavedLoginInfor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SavedLoginInfor.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SavedLoginInfor.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SavedLoginInfor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_SavedLoginInfor.Font = new System.Drawing.Font("Segoe UI Semibold", 13.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_SavedLoginInfor.ForeColor = System.Drawing.Color.White;
            this.btn_SavedLoginInfor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_SavedLoginInfor.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_SavedLoginInfor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_SavedLoginInfor.IconMarginLeft = 11;
            this.btn_SavedLoginInfor.IconPadding = 10;
            this.btn_SavedLoginInfor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_SavedLoginInfor.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_SavedLoginInfor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_SavedLoginInfor.IconSize = 25;
            this.btn_SavedLoginInfor.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedLoginInfor.IdleBorderRadius = 10;
            this.btn_SavedLoginInfor.IdleBorderThickness = 1;
            this.btn_SavedLoginInfor.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedLoginInfor.IdleIconLeftImage = null;
            this.btn_SavedLoginInfor.IdleIconRightImage = null;
            this.btn_SavedLoginInfor.IndicateFocus = false;
            this.btn_SavedLoginInfor.Location = new System.Drawing.Point(1007, 282);
            this.btn_SavedLoginInfor.Name = "btn_SavedLoginInfor";
            this.btn_SavedLoginInfor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SavedLoginInfor.OnDisabledState.BorderRadius = 10;
            this.btn_SavedLoginInfor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedLoginInfor.OnDisabledState.BorderThickness = 1;
            this.btn_SavedLoginInfor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SavedLoginInfor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SavedLoginInfor.OnDisabledState.IconLeftImage = null;
            this.btn_SavedLoginInfor.OnDisabledState.IconRightImage = null;
            this.btn_SavedLoginInfor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(181)))), ((int)(((byte)(116)))));
            this.btn_SavedLoginInfor.onHoverState.BorderRadius = 10;
            this.btn_SavedLoginInfor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedLoginInfor.onHoverState.BorderThickness = 1;
            this.btn_SavedLoginInfor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(181)))), ((int)(((byte)(116)))));
            this.btn_SavedLoginInfor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_SavedLoginInfor.onHoverState.IconLeftImage = null;
            this.btn_SavedLoginInfor.onHoverState.IconRightImage = null;
            this.btn_SavedLoginInfor.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedLoginInfor.OnIdleState.BorderRadius = 10;
            this.btn_SavedLoginInfor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedLoginInfor.OnIdleState.BorderThickness = 1;
            this.btn_SavedLoginInfor.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedLoginInfor.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_SavedLoginInfor.OnIdleState.IconLeftImage = null;
            this.btn_SavedLoginInfor.OnIdleState.IconRightImage = null;
            this.btn_SavedLoginInfor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedLoginInfor.OnPressedState.BorderRadius = 10;
            this.btn_SavedLoginInfor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SavedLoginInfor.OnPressedState.BorderThickness = 1;
            this.btn_SavedLoginInfor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(201)))), ((int)(((byte)(154)))));
            this.btn_SavedLoginInfor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_SavedLoginInfor.OnPressedState.IconLeftImage = null;
            this.btn_SavedLoginInfor.OnPressedState.IconRightImage = null;
            this.btn_SavedLoginInfor.Size = new System.Drawing.Size(77, 50);
            this.btn_SavedLoginInfor.TabIndex = 131;
            this.btn_SavedLoginInfor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_SavedLoginInfor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_SavedLoginInfor.TextMarginLeft = 0;
            this.btn_SavedLoginInfor.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_SavedLoginInfor.UseDefaultRadiusAndThickness = true;
            this.btn_SavedLoginInfor.Click += new System.EventHandler(this.btn_SavedLoginInfor_Click);
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel9.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel9.Location = new System.Drawing.Point(445, 158);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(151, 20);
            this.bunifuLabel9.TabIndex = 136;
            this.bunifuLabel9.Text = "Nhập lại mật khẩu mới";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_RetypeNewPassword
            // 
            this.txt_RetypeNewPassword.AcceptsReturn = false;
            this.txt_RetypeNewPassword.AcceptsTab = false;
            this.txt_RetypeNewPassword.AnimationSpeed = 200;
            this.txt_RetypeNewPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_RetypeNewPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_RetypeNewPassword.BackColor = System.Drawing.Color.Transparent;
            this.txt_RetypeNewPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_RetypeNewPassword.BackgroundImage")));
            this.txt_RetypeNewPassword.BorderColorActive = System.Drawing.Color.White;
            this.txt_RetypeNewPassword.BorderColorDisabled = System.Drawing.Color.White;
            this.txt_RetypeNewPassword.BorderColorHover = System.Drawing.Color.White;
            this.txt_RetypeNewPassword.BorderColorIdle = System.Drawing.Color.White;
            this.txt_RetypeNewPassword.BorderRadius = 10;
            this.txt_RetypeNewPassword.BorderThickness = 1;
            this.txt_RetypeNewPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_RetypeNewPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_RetypeNewPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_RetypeNewPassword.DefaultText = "";
            this.txt_RetypeNewPassword.FillColor = System.Drawing.Color.White;
            this.txt_RetypeNewPassword.HideSelection = true;
            this.txt_RetypeNewPassword.IconLeft = null;
            this.txt_RetypeNewPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_RetypeNewPassword.IconPadding = 10;
            this.txt_RetypeNewPassword.IconRight = null;
            this.txt_RetypeNewPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_RetypeNewPassword.Lines = new string[0];
            this.txt_RetypeNewPassword.Location = new System.Drawing.Point(445, 184);
            this.txt_RetypeNewPassword.MaxLength = 32767;
            this.txt_RetypeNewPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_RetypeNewPassword.Modified = false;
            this.txt_RetypeNewPassword.Multiline = false;
            this.txt_RetypeNewPassword.Name = "txt_RetypeNewPassword";
            stateProperties25.BorderColor = System.Drawing.Color.White;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_RetypeNewPassword.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.White;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_RetypeNewPassword.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.White;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_RetypeNewPassword.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.White;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_RetypeNewPassword.OnIdleState = stateProperties28;
            this.txt_RetypeNewPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txt_RetypeNewPassword.PasswordChar = '●';
            this.txt_RetypeNewPassword.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(85)))), ((int)(((byte)(90)))));
            this.txt_RetypeNewPassword.PlaceholderText = "Mật khẩu mới";
            this.txt_RetypeNewPassword.ReadOnly = false;
            this.txt_RetypeNewPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_RetypeNewPassword.SelectedText = "";
            this.txt_RetypeNewPassword.SelectionLength = 0;
            this.txt_RetypeNewPassword.SelectionStart = 0;
            this.txt_RetypeNewPassword.ShortcutsEnabled = true;
            this.txt_RetypeNewPassword.Size = new System.Drawing.Size(300, 50);
            this.txt_RetypeNewPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_RetypeNewPassword.TabIndex = 135;
            this.txt_RetypeNewPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_RetypeNewPassword.TextMarginBottom = 0;
            this.txt_RetypeNewPassword.TextMarginLeft = 10;
            this.txt_RetypeNewPassword.TextMarginTop = 0;
            this.txt_RetypeNewPassword.TextPlaceholder = "Mật khẩu mới";
            this.txt_RetypeNewPassword.UseSystemPasswordChar = true;
            this.txt_RetypeNewPassword.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel8.Location = new System.Drawing.Point(25, 158);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(91, 20);
            this.bunifuLabel8.TabIndex = 134;
            this.bunifuLabel8.Text = "Mật khẩu mới";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_NewPassword
            // 
            this.txt_NewPassword.AcceptsReturn = false;
            this.txt_NewPassword.AcceptsTab = false;
            this.txt_NewPassword.AnimationSpeed = 200;
            this.txt_NewPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_NewPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_NewPassword.BackColor = System.Drawing.Color.Transparent;
            this.txt_NewPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_NewPassword.BackgroundImage")));
            this.txt_NewPassword.BorderColorActive = System.Drawing.Color.White;
            this.txt_NewPassword.BorderColorDisabled = System.Drawing.Color.White;
            this.txt_NewPassword.BorderColorHover = System.Drawing.Color.White;
            this.txt_NewPassword.BorderColorIdle = System.Drawing.Color.White;
            this.txt_NewPassword.BorderRadius = 10;
            this.txt_NewPassword.BorderThickness = 1;
            this.txt_NewPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_NewPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_NewPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_NewPassword.DefaultText = "";
            this.txt_NewPassword.FillColor = System.Drawing.Color.White;
            this.txt_NewPassword.HideSelection = true;
            this.txt_NewPassword.IconLeft = null;
            this.txt_NewPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_NewPassword.IconPadding = 10;
            this.txt_NewPassword.IconRight = null;
            this.txt_NewPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_NewPassword.Lines = new string[0];
            this.txt_NewPassword.Location = new System.Drawing.Point(25, 184);
            this.txt_NewPassword.MaxLength = 32767;
            this.txt_NewPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_NewPassword.Modified = false;
            this.txt_NewPassword.Multiline = false;
            this.txt_NewPassword.Name = "txt_NewPassword";
            stateProperties29.BorderColor = System.Drawing.Color.White;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_NewPassword.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.White;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_NewPassword.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.White;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_NewPassword.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.White;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_NewPassword.OnIdleState = stateProperties32;
            this.txt_NewPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txt_NewPassword.PasswordChar = '●';
            this.txt_NewPassword.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(85)))), ((int)(((byte)(90)))));
            this.txt_NewPassword.PlaceholderText = "Mật khẩu mới";
            this.txt_NewPassword.ReadOnly = false;
            this.txt_NewPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_NewPassword.SelectedText = "";
            this.txt_NewPassword.SelectionLength = 0;
            this.txt_NewPassword.SelectionStart = 0;
            this.txt_NewPassword.ShortcutsEnabled = true;
            this.txt_NewPassword.Size = new System.Drawing.Size(300, 50);
            this.txt_NewPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_NewPassword.TabIndex = 133;
            this.txt_NewPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_NewPassword.TextMarginBottom = 0;
            this.txt_NewPassword.TextMarginLeft = 10;
            this.txt_NewPassword.TextMarginTop = 0;
            this.txt_NewPassword.TextPlaceholder = "Mật khẩu mới";
            this.txt_NewPassword.UseSystemPasswordChar = true;
            this.txt_NewPassword.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel7.Location = new System.Drawing.Point(25, 44);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(37, 20);
            this.bunifuLabel7.TabIndex = 132;
            this.bunifuLabel7.Text = "Email";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_StaffEmail
            // 
            this.txt_StaffEmail.AcceptsReturn = false;
            this.txt_StaffEmail.AcceptsTab = false;
            this.txt_StaffEmail.AnimationSpeed = 200;
            this.txt_StaffEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_StaffEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_StaffEmail.BackColor = System.Drawing.Color.Transparent;
            this.txt_StaffEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_StaffEmail.BackgroundImage")));
            this.txt_StaffEmail.BorderColorActive = System.Drawing.Color.White;
            this.txt_StaffEmail.BorderColorDisabled = System.Drawing.Color.White;
            this.txt_StaffEmail.BorderColorHover = System.Drawing.Color.White;
            this.txt_StaffEmail.BorderColorIdle = System.Drawing.Color.White;
            this.txt_StaffEmail.BorderRadius = 10;
            this.txt_StaffEmail.BorderThickness = 1;
            this.txt_StaffEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_StaffEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_StaffEmail.DefaultText = "";
            this.txt_StaffEmail.FillColor = System.Drawing.Color.White;
            this.txt_StaffEmail.HideSelection = true;
            this.txt_StaffEmail.IconLeft = null;
            this.txt_StaffEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffEmail.IconPadding = 10;
            this.txt_StaffEmail.IconRight = null;
            this.txt_StaffEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_StaffEmail.Lines = new string[0];
            this.txt_StaffEmail.Location = new System.Drawing.Point(25, 70);
            this.txt_StaffEmail.MaxLength = 32767;
            this.txt_StaffEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_StaffEmail.Modified = false;
            this.txt_StaffEmail.Multiline = false;
            this.txt_StaffEmail.Name = "txt_StaffEmail";
            stateProperties33.BorderColor = System.Drawing.Color.White;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffEmail.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.White;
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_StaffEmail.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.White;
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffEmail.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.White;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_StaffEmail.OnIdleState = stateProperties36;
            this.txt_StaffEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txt_StaffEmail.PasswordChar = '\0';
            this.txt_StaffEmail.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(85)))), ((int)(((byte)(90)))));
            this.txt_StaffEmail.PlaceholderText = "Email";
            this.txt_StaffEmail.ReadOnly = false;
            this.txt_StaffEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_StaffEmail.SelectedText = "";
            this.txt_StaffEmail.SelectionLength = 0;
            this.txt_StaffEmail.SelectionStart = 0;
            this.txt_StaffEmail.ShortcutsEnabled = true;
            this.txt_StaffEmail.Size = new System.Drawing.Size(300, 50);
            this.txt_StaffEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_StaffEmail.TabIndex = 131;
            this.txt_StaffEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_StaffEmail.TextMarginBottom = 0;
            this.txt_StaffEmail.TextMarginLeft = 10;
            this.txt_StaffEmail.TextMarginTop = 0;
            this.txt_StaffEmail.TextPlaceholder = "Email";
            this.txt_StaffEmail.UseSystemPasswordChar = false;
            this.txt_StaffEmail.WordWrap = true;
            // 
            // Settings
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(254)))));
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Name = "Settings";
            this.Size = new System.Drawing.Size(1138, 800);
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox txt_StaffSalary;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox txt_StaffAddress;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox txt_StaffPersonalID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txt_StaffPhone;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txt_StaffName;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox txt_StaffID;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_SavedStaffInfors;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_SavedLoginInfor;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox txt_RetypeNewPassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox txt_NewPassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox txt_StaffEmail;
    }
}
